### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by saranshgrover** [cubing/algdb#18]
@lgarron assigning you to this

**Comment by lgarron** [comment]
Would you be happy with a GPL license?

That's the same as cubing.js, and is basically "you can use this for whatever you want, as long as you share your code as well".

**Comment by saranshgrover** [comment]
Yup, should work

**Comment by coder13** [comment]
This can be closed?

**Comment by lgarron** [comment]
> This can be closed?

Yeah, thanks!

(I referenced this issue in my commit, but not using language that auto-closes it.)
