### ISSUE TITLE
Set up CI and automatic deployment

### ISSUE THREAD

**Issue by lgarron** [cubing/algdb#2]
Using GitHub Actions: https://github.com/features/actions

Requires having a server (#1).

One idea:
- Auto-deploy `main` to a staging server.
- Have a manual event to deploy to production.

**Comment by saranshgrover** [comment]
this is done? @big213

**Comment by big213** [comment]
Yep! As of e77021c34edf85de1c8f5b9ed1856d7b50b8cb94
